############################################################################
# ETHERNET CONFIGURATION
############################################################################

# my computer ethernet port (check this via 'ifconfig')
ethernet: "enx00e04c68005e"    # desktop dock
# ethernet: "enx207bd29d4768"  # ugreen ethernet adapter
# ethernet: "enx9cebe83faea0" # amber ethernet adapter

############################################################################
# OPERATION MODE
############################################################################

# operation mode of the motor controllers (TODO: right now 8->10)
OpMode: 8       # 8: Position Mode, 10: Torque Mode
frequency: 1000  # [Hz]

############################################################################
# PROGRAM TIME
############################################################################

# max testing time [sec]
max_prog_time: 15.0

############################################################################
# JOINT LIMITS
############################################################################

# configuration limits [rad], velocity limits [rad/s]
limits:

  # Hip Frontal Left (HFL)
  HFL:
    q_min: -0.15
    q_max: 0.15

  # Hip Sagittal Left (HSL)
  HSL:
    q_min: -0.5
    q_max: 0.35

  # Knee Left (KL)
  KL:
    q_min: -0.35
    q_max: 0.35

  # Hip Frontal Right (HFR)
  HFR:
    q_min: -0.15
    q_max: 0.15

  # Hip Sagittal Right (HSR)
  HSR:
    q_min: -0.5
    q_max: 0.35

  # Knee Right (KR)
  KR:
    q_min: -0.35
    q_max: 0.35

