############################################################################

# my computer ethernet port (check this via 'ifconfig')
ethernet: "enx00e04c68005e"

############################################################################

# Low Level Joint controller gains
Kp: 0.1          # Proportional gain
Kd: 0.01         # Derivative gain
ff_scalar: 0.0   # Feedforward scalar multiplier (positive number)

############################################################################

