############################################################################

# my computer ethernet port (check this via 'ifconfig')
ethernet: "enx00e04c68005e"
# ethernet: "enx207bd29d4768"

############################################################################

# Low Level Joint controller gains
gains:

  Kp_HFL: 0.0   # Hip Frontal Left (HFL)
  Kp_HSL: 0.0   # Hip Sagittal Left (HSL)
  Kp_KL:  0.0   # Knee Left (KL)
  Kp_HFR: 0.0   # Hip Frontal Right (HFR)
  Kp_HSR: 0.0   # Hip Sagittal Right (HSR)
  Kp_KR:  0.0   # Knee Right (KR)

  Kd_HFL: 0.0   # Hip Frontal Left (HFL)
  Kd_HSL: 0.0   # Hip Sagittal Left (HSL)
  Kd_KL:  0.0   # Knee Left (KL)
  Kd_HFR: 0.0   # Hip Frontal Right (HFR)
  Kd_HSR: 0.0   # Hip Sagittal Right (HSR)
  Kd_KR:  0.0   # Knee Right (KR)

  Kff_HFL: 0.0   # Hip Frontal Left (HFL)
  Kff_HSL: 0.0   # Hip Sagittal Left (HSL)
  Kff_KL:  0.0   # Knee Left (KL)
  Kff_HFR: 0.0   # Hip Frontal Right (HFR)
  Kff_HSR: 0.0   # Hip Sagittal Right (HSR)
  Kff_KR:  0.0   # Knee Right (KR)

############################################################################



