############################################################################

# my computer ethernet port (check this via 'ifconfig')
ethernet: "enx00e04c68005e"

############################################################################

# joint limits for the robot (DO NOT TOUCH)
HIP_FRONTAL_MIN: -0.1
HIP_FRONTAL_MAX:  0.1

KNEE_SAGITTAL_MIN: -0.1
KNEE_SAGITTAL_MAX:  0.1

HIP_SAGITTAL_MIN: -0.1
HIP_SAGITTAL_MAX:  0.1

############################################################################

