############################################################################
# ETHERNET CONFIGURATION
############################################################################

# my computer ethernet port (check this via 'ifconfig')
ethernet: "enx00e04c68005e"    # desktop dock
# ethernet: "enx207bd29d4768"  # ugreen ethernet adapter
# ethernet: "enx9cebe83faea0" # amber ethernet adapter

############################################################################
# OPERATION MODE
############################################################################

# operation mode of the motor controllers (TODO: right now 8->10)
OpMode: 10

############################################################################
# PROGRAM TIME
############################################################################

# max testing time [sec]
max_prog_time: 10.0

############################################################################
# JOINT GAINS
############################################################################

# Low Level Joint controller gains
gains:

  # Hip Frontal Left (HFL)
  HFL:
    Kp: 1500.0
    Kd: 50.0
    Kff: 0.0

  # Hip Sagittal Left (HSL)
  HSL:
    Kp: 2500.0
    Kd: 85.0
    Kff: 0.0

  # Knee Left (KL)
  KL:
    Kp: 3200.0
    Kd: 150.0
    Kff: 0.0

  # Hip Frontal Right (HFR)
  HFR:
    Kp: 0.0
    Kd: 0.0
    Kff: 0.0

  # Hip Sagittal Right (HSR)
  HSR:
    Kp: 3000.0
    Kd: 90.0
    Kff: 0.0

  # Knee Right (KR)
  KR:
    Kp: 3200.0
    Kd: 250.0
    Kff: 0.0

############################################################################
# JOINT LIMITS
############################################################################

# configuration limits [rad], velocity limits [rad/s]
limits:

  # Hip Frontal Left (HFL)
  HFL:
    q_min: -0.35
    q_max: 0.3
    qd_min: -1.0
    qd_max: 1.0

  # Hip Sagittal Left (HSL)
  HSL:
    q_min: -0.5
    q_max: 0.35
    qd_min: -1.0
    qd_max: 1.0

  # Knee Left (KL)
  KL:
    q_min: -5.0
    q_max: 5.0
    qd_min: -1.0
    qd_max: 1.0

  # Hip Frontal Right (HFR)
  HFR:
    q_min: -0.3
    q_max: 0.35
    qd_min: -1.0
    qd_max: 1.0

  # Hip Sagittal Right (HSR)
  HSR:
    q_min: -0.5
    q_max: 0.35
    qd_min: -1.0
    qd_max: 1.0

  # Knee Right (KR)
  KR:
    q_min: -0.52
    q_max: 0.52
    qd_min: -1.0
    qd_max: 1.0

